### ISSUE TITLE
1.3.0 fails on balance statements

### ISSUE THREAD

**Issue by cookie223** [dongfg/vscode-beancount-formatter#8]
It seems like the new rewrite fails on balance statements (or balance statements with long account names), eg.
```
2020-01-04 balance Assets:Balance:WallackManagement  1346.32 USD
```
error is in `format.js`
[2020-01-10 20:17:06.420] [exthost] [error] [dongfg.vscode-beancount-formatter] provider FAILED
[2020-01-10 20:17:06.421] [exthost] [error] RangeError: Invalid count value
	at String.repeat (<anonymous>)
	at alignBeancount (/Users/qchu6/.vscode/extensions/dongfg.vscode-beancount-formatter-1.3.0/out/format.js:106:36)
	at Object.format (/Users/qchu6/.vscode/extensions/dongfg.vscode-beancount-formatter-1.3.0/out/format.js:165:22)
	at Object.provideDocumentFormattingEdits (/Users/qchu6/.vscode/extensions/dongfg.vscode-beancount-formatter-1.3.0/out/extension.js:20:37)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:205
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:287
	at new Promise (<anonymous>)

**Comment by dongfg** [comment]
Yes, there is a bug when `currency_column` set to a small number.
Direct reason: python's string repeat grammar can accept a negative number but js not.
I will release a version as soon as possible, thank you for testing.

**Comment by dongfg** [comment]
New version `1.3.1` has been released.

**Comment by cookie223** [comment]
`1.3.1` seems still to be broken. 
Example:
```
2020-01-03 * "American Airlines" "ESHOPPING 2019 HOLIDAY BONUS"
  Income:PnC:Portal:AA
  Assets:Points:AmericanAirlines  
```
becomes:
```
ESHOPPING                                              2019 HOLIDAY BONUS"
  Income:PnC:Portal:AA
  Assets:Points:AmericanAirlines                     500.00 P_AA
```

**Comment by dongfg** [comment]
I just run the test case from `format_test.py` and my beancount files,I should do more test,
Use the older version `1.2.3` temporarily.

**Comment by dongfg** [comment]
Test with the new version `1.3.2` to see if there are still errors

**Comment by cookie223** [comment]
`1.3.2` fixes the problem! thx!
